### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by davidanthoff** [fredo-dedup/JSONSchema.jl#12]
Were the changes in 0.2 really breaking? If not, then it would be great to not make a breaking version increase so that downstream packages don't have to adjust things. A simple patch number increase seems like a better idea in that case.

**Comment by odow** [comment]
Hmm I guess not technically breaking. I just bumped to 0.2 because it added Project.toml and this package was broken on 32-bit Windows. (It also wasn't apparent how many down-stream packages used this, otherwise they would have hit the 32-bit failure.) I guess I could have made JuMP have a lower bound of "0.1.2" instead. 

Is there something I can do to fix this? Or is this an FYI for future reference.

**Comment by davidanthoff** [comment]
Just a FYI for the future :)
