### ISSUE TITLE
Adding more structure to the schema

### ISSUE THREAD

**Issue by kskyten** [fredo-dedup/JSONSchema.jl#6]
It would be nice to have more structure in the schema object. Currently it is only a container for the schema dict. The use case I'm thinking of, is converting Julia types into JSON schemas and generating parsers for a given schema. Here is a very rough and incomplete sketch to give you the idea (I'm not very familiar with the JSON schema specs):
```julia
struct Schema
    schema :: String
    id :: String
    definitions :: Vector
end

struct Property
    name :: String
end

struct Object
    properties :: Vector{Property}
end

```

**Comment by odow** [comment]
Now that I'm more familiar with the code, the `Schema` object is just use for dispatching the initial call to `validate`. While on some level it is enticing to have a more structured schema type, I'm not sure what it would look like.

One argument for more structure is likely that it would lead to faster validation code. However, I haven't had any performance issues validating large types with a non-trivial schema (We use JSONSchema.jl to validate [MathOptFormat files](https://github.com/jump-dev/MathOptFormat/blob/master/mof.schema.json)).

In addition, due to the flexibility of the schema definition, it's likely that some of the field types of a structured schema would need to be type-unstable, mitigating some of the performance gap. (For example, it's not clear how to represent something like `oneOf` which could be literally anything in the schema.)

Therefore, I'd be in favor of closing this issue. If performance becomes an issue in the future, we can revisit the idea.

**Comment by kskyten** [comment]
I made a sketch [here](https://gist.github.com/kskyten/6e1f58538bd8d22453dfeaec61060cf9) based on https://github.com/interagent/schematic. A proper structure would be great for generating Juliia code to parse JSON based on a schema like in https://github.com/quicktype/quicktype.

The most basic version `schema.jl` is roughly working, but how do we distinguish between an undefined  boolean field for which Julia sets a boolean value and an actual value parsed from the JSON? The other two versions are trying to address this. The Schema constructor in `nothing_schema.jl` is not working for some reason, but otherwise might be suitable. I also tried Nullables but either `Parameters` or `JSON3` is clobbering the types of the fields and the struct mapping is not working recursively.

**Comment by kskyten** [comment]
As you mentioned the typing is indeed challenging. If this impacts the performance of the validation, it might have to be separated into its own module or package.

**Comment by odow** [comment]
> how do we distinguish between an undefined boolean field for which Julia sets a boolean value and an actual value parsed from the JSON?

Not sure I follow. Can you elaborate with an example?

**Comment by kskyten** [comment]
The JSON3.Mutable() trait requires that the struct has a constructor without arguments. However, if the field is boolean, an undefined field defaults to false

```julia
mutable struct A
a :: Bool
A() = new()
end

A1 = A()
A2 = A()
A2.a = false

A1.a == A2.a
```

**Comment by odow** [comment]
Closing for now because I don't think we need more structure in the `Schema` object. If someone has a case where the validating is a bottleneck, we can revisit.
